function Content() {
    return (
       <div className="container mt-3">
         <p>
          The earliest recorded human presence in modern-day Argentina dates back to the Paleolithic period.[16] The Inca Empire expanded to the northwest of the country in Pre-Columbian times. The country has its roots in Spanish colonization of the region during the 16th century.[17] Argentina rose as the successor state of the Viceroyalty of the Río de la Plata,[18] a Spanish overseas viceroyalty founded in 1776. The declaration and fight for independence (1810–1818) was followed by an extended civil war that lasted until 1861, culminating in the country's reorganization as a federation. The country thereafter enjoyed relative peace and stability, with several waves of European immigration, mainly Italians and Spaniards, radically reshaping its cultural and demographic outlook; over 60% of the population has full or partial Italian ancestry,[19][20][21] and Argentine culture has significant connections to Italian culture.[22]
         </p>
         <p>
          The earliest recorded human presence in modern-day Argentina dates back to the Paleolithic period.[16] The Inca Empire expanded to the northwest of the country in Pre-Columbian times. The country has its roots in Spanish colonization of the region during the 16th century.[17] Argentina rose as the successor state of the Viceroyalty of the Río de la Plata,[18] a Spanish overseas viceroyalty founded in 1776. The declaration and fight for independence (1810–1818) was followed by an extended civil war that lasted until 1861, culminating in the country's reorganization as a federation. The country thereafter enjoyed relative peace and stability, with several waves of European immigration, mainly Italians and Spaniards, radically reshaping its cultural and demographic outlook; over 60% of the population has full or partial Italian ancestry,[19][20][21] and Argentine culture has significant connections to Italian culture.[22]
         </p>
         <p>
          The earliest recorded human presence in modern-day Argentina dates back to the Paleolithic period.[16] The Inca Empire expanded to the northwest of the country in Pre-Columbian times. The country has its roots in Spanish colonization of the region during the 16th century.[17] Argentina rose as the successor state of the Viceroyalty of the Río de la Plata,[18] a Spanish overseas viceroyalty founded in 1776. The declaration and fight for independence (1810–1818) was followed by an extended civil war that lasted until 1861, culminating in the country's reorganization as a federation. The country thereafter enjoyed relative peace and stability, with several waves of European immigration, mainly Italians and Spaniards, radically reshaping its cultural and demographic outlook; over 60% of the population has full or partial Italian ancestry,[19][20][21] and Argentine culture has significant connections to Italian culture.[22]
         </p>
         <p>
          The earliest recorded human presence in modern-day Argentina dates back to the Paleolithic period.[16] The Inca Empire expanded to the northwest of the country in Pre-Columbian times. The country has its roots in Spanish colonization of the region during the 16th century.[17] Argentina rose as the successor state of the Viceroyalty of the Río de la Plata,[18] a Spanish overseas viceroyalty founded in 1776. The declaration and fight for independence (1810–1818) was followed by an extended civil war that lasted until 1861, culminating in the country's reorganization as a federation. The country thereafter enjoyed relative peace and stability, with several waves of European immigration, mainly Italians and Spaniards, radically reshaping its cultural and demographic outlook; over 60% of the population has full or partial Italian ancestry,[19][20][21] and Argentine culture has significant connections to Italian culture.[22]
         </p>
         <p>
          The earliest recorded human presence in modern-day Argentina dates back to the Paleolithic period.[16] The Inca Empire expanded to the northwest of the country in Pre-Columbian times. The country has its roots in Spanish colonization of the region during the 16th century.[17] Argentina rose as the successor state of the Viceroyalty of the Río de la Plata,[18] a Spanish overseas viceroyalty founded in 1776. The declaration and fight for independence (1810–1818) was followed by an extended civil war that lasted until 1861, culminating in the country's reorganization as a federation. The country thereafter enjoyed relative peace and stability, with several waves of European immigration, mainly Italians and Spaniards, radically reshaping its cultural and demographic outlook; over 60% of the population has full or partial Italian ancestry,[19][20][21] and Argentine culture has significant connections to Italian culture.[22]
         </p>
        </div>
    )
}

export default Content;